#!/usr/bin/python3.6

if __name__ == "__main__":
    line = ""
    while "enclave_hash.m" not in line:
        line = input()
    mr_enclave = list()
    line = input()
    while line.startswith("0x"):
        mr_enclave += line.strip().split()
        line = input()
    mr_enclave = "".join(map(lambda x: x.replace("0x",""), mr_enclave))
    print("MRENCLAVE: {}".format(mr_enclave))